# Generated by Django 3.0.3 on 2020-04-01 02:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='pic',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='user_profile_pics'),
            preserve_default=False,
        ),
    ]
